# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Questionnaire.create([
{ question: %q<There is a God or gods which influence the world>},
{ question: %q<If we don’t move to green technologies we will destroy the world>},
{ question: %q<Humans can make a perfect world>},
{ question: %q<We would be better off if there were no new technologies>},
{ question: %q<People who suffer natural disasters probably had it coming>},
{ question: %q<It is better if economies don’t keep growing>},
{ question: %q<History tells us where we have been to guide where we are going>},
{ question: %q<It is not wrong to take your own life>},
{ question: %q<My family is anyone with the same last name>},
{ question: %q<All human life has value>},
{ question: %q<Life is a struggle to discover my purpose>},
{ question: %q<There are some things we can never know>},
{ question: %q<Heaven is a real place>},
{ question: %q<The role of a corporation is to maximize shareholder value>},
{ question: %q<Animals are as intelligent as humans>},
{ question: %q<Large organizations are always corrupt>},
{ question: %q<There is a God but He only helps those who help themselves>},
{ question: %q<Poverty results from poor decisions>},
{ question: %q<Small scale mining is better than large scale mining>},
{ question: %q<Kids who are bullied should suck it up or fight back>},
{ question: %q<We have to act to save the earth>},
{ question: %q<Laws should reflect the culture>},
{ question: %q<Things like ‘do not steal’ are always true>},
{ question: %q<If I had to choose a human or a whale I would choose the whale>},
{ question: %q<Evil exists and some people are evil>},
{ question: %q<If we can’t touch, smell, taste, see or hear it, it doesn’t exist>},
{ question: %q<Complex things are mostly reliable>},
{ question: %q<War is always wrong>},
{ question: %q<God loves me and cares about me>},
{ question: %q<Human intelligence has not changed over millions of years>},
{ question: %q<The gods will answer if you ask them properly>},
{ question: %q<The world is evolved by internal influences>},
{ question: %q<There is no way of knowing whether anything exists>},
{ question: %q<I don’t believe horoscopes but read them because you never know>},
{ question: %q<Humans are really just a plague>},
{ question: %q<Knowing history is interesting but not important>},
{ question: %q<People should obey laws even if they think the laws are harmful>},
{ question: %q<We are responsible to protect the environment>},
{ question: %q<Life is about the survival of the fittest>},
{ question: %q<I need my cell phone>},
{ question: %q<Governments are necessary to build good societies>},
{ question: %q<The world would be perfect if humans were not in it>},
{ question: %q<People who get aid should have to work for it>},
{ question: %q<Animals build more sustainable worlds than humans>},
{ question: %q<Everyone is responsible for their own retirement/health care>},
{ question: %q<Life on earth is a taste of life to come>},
{ question: %q<Taxes should be used to reduce income disparity>},
{ question: %q<Life just happens and I want to enjoy what I can>},
{ question: %q<The government is responsible for my retirement/health care>},
{ question: %q<Humans are apes without hair>},
{ question: %q<Some human life has limited or no value>},
{ question: %q<The world is evolving as it should>},
{ question: %q<Economies are built on technological advance>},
{ question: %q<People who don’t know history are doomed to repeat it>},
{ question: %q<Our lives are better because of technological advances>},
{ question: %q<Science and technology have given us control over the world>},
{ question: %q<The problem is not shortage but distribution of resources>},
{ question: %q<There may be a God or gods but they have no influence over me>},
{ question: %q<Humans can destroy the earth>},
{ question: %q<The world is a scary and uncontrollable place>},
{ question: %q<Aboriginal cultures are better than Western cultures>},
{ question: %q<Resource development destroys the environment>},
{ question: %q<I want to make the world a better place>},
{ question: %q<History is boring and irrelevant>},
{ question: %q<Technology is a curse>},
{ question: %q<I like finding out more information about my family>},
{ question: %q<The world was created by external forces>},
{ question: %q<I will do anything to protect my family>},
{ question: %q<I prefer to work than to retire>},
{ question: %q<I was born to love and be loved; and then I die>},
{ question: %q<Everyone should pay taxes>},
{ question: %q<When I die my body will rot and I will cease to be>},
{ question: %q<The more we try to save the earth the more damage we do>},
{ question: %q<Humans always mess things up>},
{ question: %q<Everyone is corrupt if they get the chance>},
{ question: %q<There is something wrong with the world>},
{ question: %q<Wealthy people should pay higher taxes than poor people>},
{ question: %q<I was born for a purpose>},
{ question: %q<The government should help poor people>},
{ question: %q<We can live without resource development>},
{ question: %q<Corporations care about profits and not people>},
{ question: %q<History is a circular story that keeps repeating itself>},
{ question: %q<There is no natural law>},
{ question: %q<Whether stealing is wrong depends upon the situation>},
{ question: %q<I don’t trust authority>},
{ question: %q<I was born to make money and live well>},
{ question: %q<Governments should have defined and restricted roles>},
{ question: %q<Poverty makes people do bad things>},
{ question: %q<There is more to the world than what our senses take in>},
{ question: %q<Increasing complexity leads to a tipping point into chaos>},
{ question: %q<Inti Raymi is real>},
{ question: %q<In the future there will be nothing humans won’t know>},
{ question: %q<Capital punishment is wrong>},
{ question: %q<It is ok to sacrifice animals to improve the chances of finding gold>},
{ question: %q<My family should help me in my retirement>},
{ question: %q<We can prove that we exist>},
{ question: %q<I am on my own in this world and it is up to me>},
{ question: %q<Sometimes war is necessary to stop madmen>},
{ question: %q<All people are basically good>},
{ question: %q<Human life is more important than anything else>},
{ question: %q<All cultures are morally equivalent>},
{ question: %q<Justice is for the rich>},
{ question: %q<There is no moral truth>},
{ question: %q<Mountain gods control access to gold and silver>},
{ question: %q<The earth will heal itself no matter what we do>},
{ question: %q<Bullies should be punished>},
{ question: %q<My family consists of my children and spouse>},
{ question: %q<Members of NGO’s should be on corporate boards>},
{ question: %q<The world can never be made perfect>},
{ question: %q<Large corporations are always corrupt>},
{ question: %q<There is no purpose to my or anyone’s life>},
{ question: %q<Third World nations should require corporations to deliver justice>},
{ question: %q<There is nothing seriously wrong with humanity>},
{ question: %q<There should be fewer laws which don’t change>},
{ question: %q<I believe in Heaven and Hell>},
{ question: %q<I would pay higher taxes to reduce homelessness>},
{ question: %q<There is no such place as Heaven or Hell>},
{ question: %q<I can’t wait to retire>},
{ question: %q<The people I live with are my family>},
{ question: %q<We will continue to evolve and get more intelligent>},
{ question: %q<History has a beginning and an end>},
{ question: %q<A simple life is better than a materialistic life>},
{ question: %q<History is a construct and real history can’t be known>},
{ question: %q<Life begins at conception>},
{ question: %q<Burning trees helps the rains come>},
{ question: %q<The worlds resources are disappearing>},
{ question: %q<Resource development is necessary to our way of life>},
{ question: %q<Only people and not organizations can be corrupt>},
{ question: %q<There is no such thing as God or gods>},
{ question: %q<There is no shortage of oil in the world>},
{ question: %q<What works in one culture may not work in another>},
{ question: %q<Science and reason are more important than faith and superstition>},
{ question: %q<We can’t prove that we exist>},
{ question: %q<Complex things are mostly unreliable>},
{ question: %q<Strong economies are built on moral foundations>},
{ question: %q<If a policeman told me to kill or be killed, I would kill>},
{ question: %q<Only people who pay taxes should vote>},
{ question: %q<The courts will protect poor people>},
{ question: %q<The environment is more important than humans>},
{ question: %q<The more we know, the more we know what we don’t know>},
{ question: %q<New technologies will always help us keep costs down>},
{ question: %q<Humans are the most important thing>},
{ question: %q<Competition is the basis of a strong economy>},
{ question: %q<There is a God or gods which influence the world>},
{ question: %q<If we don’t move to green technologies we will destroy the world>},
{ question: %q<Humans can make a perfect world>},
{ question: %q<We would be better off if there were no new technologies>},
{ question: %q<People who suffer natural disasters probably had it coming>},
{ question: %q<It is better if economies don’t keep growing>},
{ question: %q<History tells us where we have been to guide where we are going>},
{ question: %q<It is not wrong to take your own life>},
{ question: %q<My family is anyone with the same last name>},
{ question: %q<All human life has value>},
{ question: %q<Life is a struggle to discover my purpose>},
{ question: %q<There are some things we can never know>},
{ question: %q<Heaven is a real place>},
{ question: %q<The role of a corporation is to maximize shareholder value>},
{ question: %q<Animals are as intelligent as humans>},
{ question: %q<Large organizations are always corrupt>},
{ question: %q<There is a God but He only helps those who help themselves>},
{ question: %q<Poverty results from poor decisions>},
{ question: %q<Small scale mining is better than large scale mining>},
{ question: %q<Kids who are bullied should suck it up or fight back>},
{ question: %q<We have to act to save the earth>},
{ question: %q<Laws should reflect the culture>},
{ question: %q<Things like ‘do not steal’ are always true>},
{ question: %q<If I had to choose a human life or a whale’s live I would choose the whale>},
{ question: %q<Evil exists and some people are evil>},
{ question: %q<If we can’t touch, smell, taste, see or hear it, it doesn’t exist>}
])

Moderator.create(name: "snowden", password: "password")
